config/routes.rb
Rails.application.routes.draw do
  root 'advertisements#landing'
  resources :comments
  resources :advertisements
  # login and logout routes
  get 'users/login' => 'users#login'
  post 'users/login' => 'users#login_check'
  get 'users/logout' => 'users#logout'

  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/advertisement.rb
class Advertisement < ApplicationRecord
  validates :title, presence: true
  validates :price, presence: true
  validates :content, presence: true

  belongs_to :user
  has_many :comments
end

app/controllers/advertisements_controller.rb
class AdvertisementsController < ApplicationController
  before_action :set_advertisement, only: [:show, :edit, :update, :destroy]
  helper_method :advertisement_content_checker

  def landing
    @how_many_published_ads = Advertisement.where(:published => true).count
    @how_many_com = Comment.count
  end

  # GET /advertisements
  # GET /advertisements.json
  # checking what's the user's role to see if they can have access to unpublished stuff
  def index
    @how_many_published_ads = Advertisement.where(:published => true).count
    if @current_user != nil && @current_user.role == 'admin'
      @advertisements = Advertisement.all
    else
      @advertisements = Advertisement.where(published: true)
    end
  end

  # GET /advertisements/1
  # GET /advertisements/1.json
  def show
    # checking if the person who accesses the unpublished advertisements is an admin
    @advertiser = User.find(@advertisement.user_id)
    if @advertisement.published == false && session[:user_id] == nil || @advertisement.published == false && @current_user.role != "admin"
      flash[:not_admin] = "Vous ne faites pas partie de l'équipe d'administration !"
      return redirect_to "/advertisements"
    else
    end
    # part of the show action that is about comments
    @comment = Comment.new
    @comments = Comment.where(advertisement_id: @advertisement.id)
  end

  # GET /advertisements/new
  def new
    if defined? @current_user.name
      @advertisement = Advertisement.new
    else
      flash[:need_to_connect] = "Il faut se connecter !"
      return redirect_to "/users/login"
    end
  end

  # GET /advertisements/1/edit
  def edit
    if session[:user_id] == nil || @current_user.role != 'admin'
      flash[:not_admin] = "Vous ne faites pas partie de l'équipe d'administration !"
      redirect_to "/advertisements"
    else
    end
  end

  # POST /advertisements
  # POST /advertisements.json
  def create
    if advertisement_params[:published] == nil
      @advertisement = Advertisement.new(advertisement_params.merge!(published: false, user_id: session[:user_id]))
    else
      @advertisement = Advertisement.new(advertisement_params)
    end

    respond_to do |format|
      if @advertisement.save
        format.html { redirect_to advertisements_path, notice: "L'annonce a bien été créé." }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /advertisements/1
  # PATCH/PUT /advertisements/1.json
  def update
    respond_to do |format|
      if @advertisement.update(advertisement_params)
        format.html { redirect_to @advertisement, notice: "L'annonce a été modifiée avec succès !"}
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /advertisements/1
  # DELETE /advertisements/1.json
  def destroy
    @advertisement.destroy
    respond_to do |format|
      format.html { redirect_to advertisements_url, notice: 'Advertisement was successfully destroyed.' }
    end
  end

  def advertisement_content_checker advertisement_content
    checked_advertisement_content = ""
    splitted_advertisement_content = advertisement_content.split(' ')
    if splitted_advertisement_content.count > 10
      checked_advertisement_content = splitted_advertisement_content.slice(0,10).push("...").join(' ')
    else
      checked_advertisement_content = advertisement_content
    end
    checked_advertisement_content
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_advertisement
      @advertisement = Advertisement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def advertisement_params
      params.require(:advertisement).permit(:title, :price, :content, :user_id, :published)
    end
end

app/helpers/advertisements_helper.rb
module AdvertisementsHelper
end

app/views/advertisements/_comments_form.html.erb
<%= form_for @comment do |f| %>

  <div class="field">
    <%= f.number_field :advertisement_id, :value => @advertisement.id, :hidden => true%>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/advertisements/_form.html.erb
<%= form_with(model: advertisement, local: true) do |form| %>
  <% if advertisement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(advertisement.errors.count, "error") %> prohibited this advertisement from being saved:</h2>

      <ul>
      <% advertisement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :advertisement_title %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, id: :advertisement_price %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :advertisement_content %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/advertisements/edit.html.erb
<section>
  <h1>Editing Advertisement</h1>

  <%= render 'form', advertisement: @advertisement %>

  <%= link_to 'Show', @advertisement %> |
  <%= link_to 'Back', advertisements_path %>
</section>

app/views/advertisements/index.html.erb
<p id="notice"><%= notice %></p>
<section class="row text-center">
  <h1 class="col-lg-12">Annonces (<%= @how_many_published_ads %>)</h1>
  <p class="col-lg-12"> <%= flash[:not_admin] %> </p>
  <div class="col-lg-4">
  </div>
  <%= link_to 'Créer une annonce', new_advertisement_path, class:"perso-link col-lg-4" %>
  <div class="col-lg-4">
  </div>
</section>
<section class="row content-row">
  <% @advertisements.each do |advertisement| %>
  <% @advertiser = User.find(advertisement.user_id) %>
    <div class="col-lg-4 text-center">
      <h2><%= advertisement.title %> | <%= @advertiser.name %> </h2>
      <p><%= advertisement.price %> euros</p>
      <p><%= advertisement_content_checker(advertisement.content) %></p>
      <p><%= link_to "détails", advertisement, class: 'perso-link btn btn-default' %></p>
    </div>
  <% end %>
</section>

app/views/advertisements/landing.html.erb
<section class="big-header text-center row">
  <h1>Les P'tites Annonces</h1>
  <h2>Il y a actuellement <em><%= @how_many_published_ads %> annonces</em> et <em><%= @how_many_com %> commentaires</em> sur Les P'tites Annonces</h2>
</section>
<section class="text-center showcase row">
  <div class="col-lg-4">
    <h2>Créez...</h2>
    <p>Très simplement votre annonce pour qu'elle soit vue par toustes !</p>
  </div>
  <div class="col-lg-4">
    <h2>Parcourez...</h2>
    <p>La liste regroupant toutes les annonces et trouvez celle qui vous intéresse !</p>
  </div>
  <div class="col-lg-4">
    <h2>Commentez...</h2>
    <p>Une annonce qui vous intéresse pour le faire savoir à son auteurice !</p>
  </div>
</section>

app/views/advertisements/new.html.erb
<section>
  <h1>New Advertisement</h1>

  <%= render 'form', advertisement: @advertisement %>

  <%= link_to 'Back', advertisements_path %>
</section>

app/views/advertisements/show.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center"><%= @advertisement.title.capitalize %></h1>

<section class="row content-row text-center">
  <div class="col-lg-12">
    <p class="popout"><strong>Prix :</strong> <%= @advertisement.price %> euros</p>
    <p><strong>Date de création :</strong> <%= @advertisement.created_at %></p>
    <p><strong>Contenu :</strong> <%= @advertisement.content %></p>
    <p><strong>Postée par :</strong> <%= @advertiser.name %>
  </p>
</section>

<% unless @advertisement.published %>
<%= button_to "Publier", advertisement_path(@advertisement, :advertisement => {:published => true}), :method => :put%>
<% end %>

<div class="separator"></div>

<section class="row text-center">
  <h2 id="comments-section">Commentaires</h2>
  <% @comments.each do |c| %>
    <div class="comment-container">
      <p class="comment">Posté par : <strong><%= User.find(c.user_id).name %></strong> | <%= c.content.capitalize %></p>
    </div>
    <% end %>
</section>
<% unless session[:user_id] == nil  %>
  <%= render 'comments_form' %>
<% end %>