config/routes.rb
Rails.application.routes.draw do
  root 'advertisements#landing'
  resources :comments
  resources :advertisements
  # login and logout routes
  get 'users/login' => 'users#login'
  post 'users/login' => 'users#login_check'
  get 'users/logout' => 'users#logout'

  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="row text-center">
  <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
    <p>Codé par <a class="perso-link" href="https://github.com/ModifiedChocolateUnicorn">ModifiedChocolateUnicorn</a></p>
  </div>
  <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
    <p>Image par <a class="perso-link" href="https://unsplash.com/photos/VDFOnAwdVjg">Robert Haverly</a></p>
  </div>
  <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
    <p>Plus d'infos <a class="perso-link" href="https://modifiedchocolateunicorn.gitlab.io/UnicornResume/">sur moi</a></p>
  </div>
</footer>

app/views/layouts/_nav.html.erb
<% if defined? @current_user.name %>
  <li class="col-lg-3 text-center"><a><%=@current_user.name %></a></li>
  <li class="col-lg-3 text-center"><%= link_to "Accueil", "/", class: 'perso-link' %></li>
  <li class="col-lg-3 text-center"><%= link_to "Annonces", advertisements_path, class: 'perso-link' %></li>
  <li class="col-lg-3 text-center"><%= link_to "Déconnexion", "#{users_path}/logout", class: 'perso-link' %></li>

<% else %>
  <li class="col-lg-4 text-center"><%= link_to "Accueil", "/", class: 'perso-link' %></li>
  <li class="col-lg-4 text-center"><%= link_to "Annonces", advertisements_path, class: 'perso-link' %></li>
  <li class="col-lg-4 text-center"><%= link_to "Connexion", "#{users_path}/login", class: 'perso-link' %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Les P'tites Annonces</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section class="container-fluid">
      <nav class="col-lg-12 navbar navbar-default navbar-fixed-top">
        <nav class="navbar navbar-default navbar-fixed-top">
          <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand">Les P'tites Annonces</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                <%= render 'layouts/nav' %>
              </ul>
            </div><!-- /.navbar-collapse -->
          </div><!-- /.container-fluid -->
        </nav>
      </nav>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </section>
  </body>
</html>